In [16]:
import numpy as np
from scipy import linalg

In [17]:
# define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

In [28]:
def PCA(A):
    mu = np.mean(A.T, axis = 1)
    N = A.shape[1]
    cov = 1/N * (A - mu).T @ (A - mu)
    values, vectors = linalg.eig(cov)
    return vectors, values

In [29]:
PCA(A)

(array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([8.+0.j, 0.+0.j]))

In [30]:
# Compare the result with the sklearn library
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(A)
print(pca.components_)
print(pca.explained_variance_)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]
